[package]
name = "yolov11"
version = "0.1.0"
edition = "2021"

[features]
default = []
cuda = ["candle-core/cuda"]

[dependencies]
candle-core = "0.8"
candle-nn = "0.8"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
image = "0.25"
rand = "0.8"
bincode = "1"
rayon = "1"
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
csv = "1"
safetensors = "0.4"
