[package]
name = "yolo-train"
version = "0.1.0"
edition = "2021"

[features]
default = []
cuda = ["candle-core/cuda", "yolo-model/cuda"]

[dependencies]
yolo-model = { path = "../yolo-model" }
yolo-data = { path = "../yolo-data" }
candle-core = { workspace = true }
candle-nn = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
csv = "1"
safetensors = "0.4"
rand = "0.8"
